name: manhal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.1
  flutter_tts: ^4.2.2
  audioplayers: ^6.1.1
  firebase_storage: ^11.7.7
  video_player: ^2.6.1
  chewie: ^1.7.0
  shared_preferences: ^2.2.2
  http: ^0.13.4
  camera: ^0.10.5+4  
  path_provider: ^2.1.2 
  permission_handler: ^11.0.1
  intl: ^0.18.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.44

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # ✅ أضفناها هنا

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/Letters.png
    - assets/images/high-volume.png
    - assets/images/letterIcon.png
    - assets/images/ethicalIcon.png
    - assets/images/scanIcon.png
    - assets/images/BackGroundManhal.jpg
    - assets/images/boy.png
    - assets/images/boy1.png
    - assets/images/boy2.png
    - assets/images/boy3.png
    - assets/images/boy4.png
    - assets/images/boy5.png
    - assets/images/girl.png
    - assets/images/girl1.png
    - assets/images/girl2.png
    - assets/images/girl3.png
    - assets/images/girl4.png
    - assets/images/girl5.png
    - assets/images/splash.png
    - assets/images/default_avatar.jpg
    - assets/images/stickers_icon.png
    - assets/images/carrot.png
    - assets/images/NumberBackground.png
    - assets/images/Pathway.png
    - assets/images/happyChick.png
    - assets/images/chick.png
    - assets/images/trophy.png
    - assets/images/editAvatar.png
    - assets/images/stopwatch.png
    - assets/images/Sad.png
    - assets/images/sleeping.png
    - assets/images/ManhalBackground2.png
    - assets/images/Lock.png

  fonts:
    - family: Blabeloo
      fonts:
        - asset: assets/fonts/Blabeloo-font-v.1.0.ttf
    - family: Uthman
      fonts:
        - asset: assets/fonts/UthmanicHafs_V22.ttf
    - family: alfont
      fonts:
        - asset: assets/fonts/alfont.otf
