// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjkKUvp4_bCgu-RQE7SkHyHwR5SON-QrI',
    appId: '1:972491493758:web:d7eb9e3700dcd19819e32f',
    messagingSenderId: '972491493758',
    projectId: 'manhal-e2276',
    authDomain: 'manhal-e2276.firebaseapp.com',
    storageBucket: 'manhal-e2276.firebasestorage.app',
    measurementId: 'G-WYV9W7EL2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-8-Fm-Huh5uuF7-FTCcRGrwSL-Tm4k4A',
    appId: '1:972491493758:android:725dcc6a281b134c19e32f',
    messagingSenderId: '972491493758',
    projectId: 'manhal-e2276',
    storageBucket: 'manhal-e2276.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1slri817CdJcuyesC76mZqM6H8j4sJ5Y',
    appId: '1:972491493758:ios:8fa1e77c82dd80a719e32f',
    messagingSenderId: '972491493758',
    projectId: 'manhal-e2276',
    storageBucket: 'manhal-e2276.firebasestorage.app',
    iosBundleId: 'com.example.manhal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1slri817CdJcuyesC76mZqM6H8j4sJ5Y',
    appId: '1:972491493758:ios:8fa1e77c82dd80a719e32f',
    messagingSenderId: '972491493758',
    projectId: 'manhal-e2276',
    storageBucket: 'manhal-e2276.firebasestorage.app',
    iosBundleId: 'com.example.manhal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjkKUvp4_bCgu-RQE7SkHyHwR5SON-QrI',
    appId: '1:972491493758:web:4018785d7a71372f19e32f',
    messagingSenderId: '972491493758',
    projectId: 'manhal-e2276',
    authDomain: 'manhal-e2276.firebaseapp.com',
    storageBucket: 'manhal-e2276.firebasestorage.app',
    measurementId: 'G-2P7SDL6ZJE',
  );
}
